### ISSUE TITLE
'could not find datetime'

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/findimports#3]
My Jenkins runs findimports, which produces errors of the form
```
src/foo.py: could not find datetime
src/bar.py: could not find datetime.date
src/baz.py: could not find datetime.datetime
src/qux.py: could not find datetime.timedelta
```

Why would it not be able to find the stdlib module?

I cannot reproduce if I run findimports locally on the same project.

**Comment by mgedmin** [comment]
The failure occurs on Ubuntu 14.04 LTS, with Python 2.7.6.
```python
>>> import datetime
>>> datetime.__file__
'/usr/lib/python2.7/lib-dynload/datetime.x86_64-linux-gnu.so'
>>> import sys
>>> 'datetime' in sys.builtin_module_names
False
```

Meanwhile on Ubuntu 14.10, with Python 2.7.8:
```python
>>> import sys
>>> 'datetime' in sys.builtin_module_names
True
>>> import datetime
>>> datetime.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'
>>> datetime.__path__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__path__'
```

and on Ubuntu 10.04 LTS, with 2.7.3:
```python
>>> import sys
>>> 'datetime' in sys.builtin_module_names
False
>>> import datetime
>>> datetime.__file__
'/usr/lib/python2.7/lib-dynload/datetime.so'
```
