### ISSUE TITLE
FileNotFoundError: __future__.py

### ISSUE THREAD

**Issue by Lightjohn** [mgedmin/findimports#7]
Just met that bug, not a big one because I think my case is special.
In my project folder there is another `virtualenv` folder and when trying to parse it :

```
Traceback (most recent call last):
  File "/home/me/myVirtualenv/bin/findimports", line 11, in <module>
    sys.exit(main())
  File "/home/me/myVirtualenv/lib/python3.6/site-packages/findimports.py", line 822, in main
    g.parsePathname(fn)
  File "/home/me/myVirtualenv/lib/python3.6/site-packages/findimports.py", line 427, in parsePathname
    self.parseFile(os.path.join(root, fn))
  File "/home/me/myVirtualenv/lib/python3.6/site-packages/findimports.py", line 454, in parseFile
    module.imported_names = find_imports(filename)
  File "/home/me/myVirtualenv/lib/python3.6/site-packages/findimports.py", line 319, in find_imports
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './localVenv/lib/python3.5/__future__.py'
```

Is it expected?

**Comment by Lightjohn** [comment]
It fact it's stupid.
Just looked inside and all python files are broken links...
So maybe you could add a check for fake files but that's not a very common case.

`__future__.py -> /usr/lib/python3.5/__future__.py`

And `/usr/lib/python3.5` does not exist anymore since my upgrade to ubuntu 18.04.

**Comment by mgedmin** [comment]
Ah, yes, the happy fun with virtualenvs during system upgrades.

I would accept a PR for making findimports emit user-friendly warning messages in this case (e.g. `WARNING: ./localVenv/lib/python3.5/__future__.py is a broken symlink`), but I'm not planning on doing any work on this myself.

**Comment by Lightjohn** [comment]
I agree, not a big impact of doing that.
Time to fix my virtualenv then...
